### ISSUE TITLE
Написать оформленное ТЗ



### ISSUE THREAD

**Issue by morozzov** [morozzov/StudentRating#3]

**Comment by morozzov** [comment]
# 1.ТЕХНИЧЕСКОЕ ЗАДАНИЕ

## 1.1.Общие сведения

### 1.1.1.Полное наименование системы

Сервис для оценки учебной и внеучебной деятельности студентов преподавателями.

### 1.1.2.Плановые сроки начала и окончания работы по созданию системы

Начало работы: 01.09.2022

Окончание работы: 01.12.2022

## 1.2.Назначение и цели создания (развития) системы

### 1.2.1.Назначение системы

Назначением системы является хранение рейтинга студентов в базе данных,его изменение и просмотр при помощи веб-сайта.

### 1.2.2.Цели создания системы

Цель создания системы – предоставить студентам мотивацию положительной деятельности, как учебной, так и внеучебной, посредством сравнения их статистики с другими студентами. Преподавателям же дать возможность направлять студентов в лучшую сторону, поощряя или штрафуя их.

## 1.3.Характеристики объекта автоматизации

Объектом автоматизации является сайт с рейтингом студентов. Автоматизированию подлежит демонстрация рейтинга всех студентов, способы получения очков рейтинга.

## 1.4.Требования к системе

### 1.4.1.Требования к системе в целом

Программный продукт должен представлять собой веб-приложением.

### 1.4.2.Требования к структуре и функционированию системы

Приложение должно быть разделено на 3 слоя:

- Слой клиентского приложения - веб-сайт;
- Слой бизнес-логики приложения - сервер;
- Слой хранения данных - база данных.

Функционал приложения должен содержать:

- Авторизацию пользователей;
- Демонстрацию списка студентов с количеством очков их рейтинга;
- Визуализацию списка активности студента на его личной странице;
- Возможность посмотреть страницы друг друга студентам;
- Показ списка поручений, за которые можно получить дополнительные баллы и возможность пометить поручение, как занятое;
- Инструменты для начисления или списания очков студентам преподавателями;
- Инструменты для создания или закрытия поручений преподавателями.

### 1.4.3.Требования к надежности

Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных.

## 1.5.Состав и содержание работ по созданию системы

| Стадии | Этапы работ | Сроки исполнения |
| --- | --- | --- |
| 1. Формирование требований к АС | 1.1. Исследование объекта и подтверждение необходимости создания АС. 1.2. Формирование требований пользователя к АС. 1.3. Оформление отчёта о выполненной работе и заявки на разработку АС. | |
| 2. Разработка концепции АС. | 2.1. Изучение выбранного объекта. 2.2. Проведение научно- исследовательских работ. 2.3. Проектирования концепции АС, удовлетворяющей потребности пользователя. 2.4. Оформление отчёта о выполненной работе. | |
| 3. Техническое задание. | Разработка и утверждение технического задания на создание АС. | |
| 4. Разработка системы. | Разработка системы согласно техническому заданию. | |
| 5. Защита курсовой работы. | 5.1. Создание грамотной презентации и речи для защиты курсовой работы. . Защита курсовой работы. | |

## 1.6.Порядок контроля и приемки системы

### 1.6.1.Состав, объем и методы испытаний системы и ее составных частей

Приложение должно пройти предварительные испытания, состоящие из отладки и минимального набора тестов.

В результате предварительных испытаний, должны быть исправлены недочеты, замечания на которые были получены в ходе предварительных испытаний.

Для проверки корректной работы внесённых изменений должны быть проведены повторные испытания разработанной системы.

### 1.6.2.Общие требования к приемке работ

В процессе приемки работ должна быть осуществлена проверка на соответствие требованиям настоящего «Технического задания». По результатам испытаний возможны доработки и исправления.

## 1.7.Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие

При подготовке объекта автоматизации к вводу системы в действие следует выполнить:

- Обеспечение работ по вводу данных в систему;
- Развертывание системы на сервере;
- Настройка системы доступа и создание учетных записей.

## 1.8.Требования к документированию

По окончании работы предъявлена расчетно-пояснительная записка, в состав которой входят:

- Техническое задание;
- Научно-исследовательская часть;
- Проектно-конструкторская часть;
- Проектно-технологическая часть.

Также должна быть предоставлена графическая часть работы, выполненная в формате А1 на 2 листах, в которую входят:

- Демонстрационные чертежи;
- Алгоритмические схемы.

## 1.9.Источники разработки

- Гост 34.601-90;
- Гост 34.602-89.

**Comment by wldmr-key** [comment]
норм. Засчитывается
