### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by morozzov** [morozzov/StudentRating#4]

**Comment by morozzov** [comment]
## Описание предметной области

Студенческий рейтинг - сервис для оценки учебной и внеучебной деятельности студентов преподавателями.

Рейтинг начинается с 0 очков и растет при положительной активности и уменьшается при отрицательной, соответственно. 

Для систематизации выставления очков используется таблица выставления очков рейтинга.

### Таблица выставления очков рейтинга
 Количество очков | Событие |
| ----------- | ----------- |
| +3 ... +5 | Итоговая успеваемость за семестр |
| +1 ... +3 | Помощь преподавателю напрямую |
| +1 ... +5 | Выполнение поручения из списка поручений |
| +1 ... +5 | Спортивная деятельность(в зависимости от степени участия) |
| +1 ... +5 | Культурная деятельность(в зависимости от степени участия) |
| +5 ... +10 | Публикация научной работы |
| +5 | Благодарность |
| -1 | Штраф за отказ от поручения |
| -1 | Опоздание на 15 минут и более |
| -2 | Долг по предмету |
| -2 | Пропуск пары без уважительной причины |
| -5 | Выговор |
| -10 ... -1 | Нарушение внутреннего распорядка ВУЗА(в зависимости от тяжести) |

В таблицу могут вноситься изменения перед началом учебного года комиссией из преподавателей и членов студсовета. 

В случае несогласия с начисленными или списанными баллами, студент может подать апелляцию. Апелляция отображается у двух случайно выбранных преподавателей и одного из студентов студсовета с возможностью принять ее условия или же нет. Апелляцию на одну активность можно подать лишь дважды, чтобы студент грамотно оценивал то, чего он хочет добиться.

Нормой является положительное количество очков рейтинга. Рейтинг действует в течении учебного года, после чего счета студентов обнуляются, но у них сохраняется количество очков за прошлый год в профиле, в разделе достижений.

Студенты могут посмотреть свой рейтинг и рейтинг других студентов. Могут ознакомиться с личными заслугами и оплошностями своими и остальных студентов. У студентов есть возможность откликаться на поручения от преподавателей, за которые получают дополнительные баллы. После отклика вносится запись в базу данных, фиксирующая причастность студента к поручению, с указанием времени отклика, статуса и, в последствии, времени выполнения.
Выполненные поручения получают соответственный статус и, в дальнейшем, могут использоваться для статистики.

Преподаватели имеют возможность вносить достижения и проступки студентов, оценивая это баллами, которые прибавляются или вычитаются из имеющихся у данного студента баллов. Внесенные данные о проступках и достижениях записываются в базу данных и называются активностью. Преподаватели добавляют поручения, оценивая их в количество баллов рейтинга. Также закрывают созданные поручения, подтверждая их выполнение или же отменяя их.

Клиентская часть представлена сайтом.

Разделы сайта:

- Главная страница со списком всех студентов, отсортированным по количеству баллов;
- Страница со списком поручений, за которые можно получить дополнительные баллы;
- Личная страница студента с его активностью.

Данные хранятся на сервере в базе данных.

**Comment by wldmr-key** [comment]
стоп! Это ни разу не инженерный подход. Что такое рейтинг? Как он рассчитывается? Как избежать субъективности? "10 очков Гриффиндору" - это не наш путь ))

**Comment by morozzov** [comment]
## Добавил следующее:


Рейтинг начинается с 0 очков и растет при положительной активности и уменьшается при отрицательной, соответственно. 

Для систематизации выставления очков используется таблица выставления очков рейтинга.

### Таблица выставления очков рейтинга
 Количество очков | Событие |
| ----------- | ----------- |
| +1 ... +3 | Помощь преподавателю напрямую |
| +1 ... +5 | Выполнение поручения из списка поручений |
| +1 ... +5 | Спортивная деятельность(в зависимости от степени участия) |
| +1 ... +5 | Культурная деятельность(в зависимости от степени участия) |
| +5 ... +10 | Публикация научной работы |
| -1 | Опоздание на 15 минут и более |
| -2 | Пропуск пары без уважительной причины |
| -5 | Выговор |
| -10 ... -1 | Нарушение внутреннего распорядка ВУЗА(в зависимости от тяжести) |

В случае несогласия с начисленными или списанными баллами, студент может подать апелляцию. Апелляция отображается у трех случайно выбранных преподавателей с возможностью принять ее условия или же нет. Апелляцию на одну активность можно подать лишь дважды, чтобы студент грамотно оценивал то, чего он хочет добиться.

**Comment by wldmr-key** [comment]
то есть, успеваемость не роялит, да?
обрати внимание - пропуск пар влияет на рейтинговую оценку студентов по каждой дисциплине

В описании предметной области имело бы смысл сказать, что студенты так или иначе получают неформальную оценку своих положительных и отрицательных поступков в группе, на кафедре, ВУЗе и т.п. Выглядит привлекательной задача сделать этот процесс более упорядоченным и открытым для всех участников учебного процесса

В апелляции имело бы смысл в качестве одного из арбитров привлекать представителя студентов имхо.

Критерии, и оценки, надеюсь, можно будет изменять в процессе развития системы.

Рейтинг не нормирован. Это хорошо?

**Comment by morozzov** [comment]
## Добавил в таблицу:
+3 ... +5 | Итоговая успеваемость за семестр
-- | --
-2 | Долг по предмету

## Добавил в текст следующее:
В таблицу могут вноситься изменения перед началом учебного года комиссией из преподавателей и членов студсовета.

В случае несогласия с начисленными или списанными баллами, студент может подать апелляцию. Апелляция отображается у двух случайно выбранных преподавателей и одного из студентов студсовета с возможностью принять ее условия или же нет. Апелляцию на одну активность можно подать лишь дважды, чтобы студент грамотно оценивал то, чего он хочет добиться.

Нормой является положительное количество очков рейтинга. Рейтинг действует в течении учебного года, после чего счета студентов обнуляются, но у них сохраняется количество очков за прошлый год в профиле, в разделе достижений.

**Comment by wldmr-key** [comment]
приемлемо. Хотелось бы, чтобы таблица рейтинговых оценок не была в хардкоде. С другой стороны, было бы не очень справедливо слишком корректировать ее в рамках оценочного периода...
