### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by morozzov** [morozzov/StudentRating#5]

**Comment by morozzov** [comment]
Аналогом разрабатываемого сервиса можно назвать систему оценок в приложении Яндекс Go.
Приложение Яндекс Go — мобильное приложение компании «Яндекс», связанное с транспортировкой и доставкой. Было создано на базе «Яндекс. Такси».
В приложении клиент имеет возможность оставить отзыв на водителя. У водителя же есть возможность оценить пассажира.
Отзывы содержат оценку от одной до пяти звезд и значки за понравившиеся в поездке детали(чистота в салоне, приятная музыка и другие) и текстовый комментарий.
Отзывы влияют на общую оценку водителя и пассажира. Оценка дает возможность заранее знать о порядочности потенциальном попутчике и сделать выводы еще до поездки.
Система отзывов позволяет избежать нежелательных инцидентов, помогают изменяться водителям и пассажирам в лучшую сторону.
Задача системы отзывов в Яндекс Go схожа с задачей разрабатываемого сервиса: и то, и другое направлено на мотивацию людей быть лучше и становиться лучше.
# 
Также похожую систему имеет образовательная система многих университетов. 
В ходе работы за семестр, студенты набирают баллы за выполнение учебных заданий. Баллы суммируются и в конце семестра по их количеству высчитывается рейтинговая оценка или же ставится зачет.
Проблема подобных систем заключается в том, что она подразумевает учет лишь учебное деятельности студентов, не беря в счет их личные качества и заслуги. Помимо этого, в подобных системах нельзя посмотреть успеваемость других студентов, что исключает фактор какого-либо соперничества, что может быть для кого-то мотивацией работать и вообще что-нибудь делать.

**Comment by wldmr-key** [comment]
Это хорошо, но мало. Следует изучить и оценить применение рейтингов в учебной и другой социальной деятельности. Оценить - это узнать не только что такое хорошо, но и что такое плохо

**Comment by morozzov** [comment]
## Добавил следующее:
Также похожую систему имеет образовательная система многих университетов.
В ходе работы за семестр, студенты набирают баллы за выполнение учебных заданий. Баллы суммируются и в конце семестра по их количеству высчитывается рейтинговая оценка или же ставится зачет.
Проблема подобных систем заключается в том, что она подразумевает учет лишь учебное деятельности студентов, не беря в счет их личные качества и заслуги. Помимо этого, в подобных системах нельзя посмотреть успеваемость других студентов, что исключает фактор какого-либо соперничества, что может быть для кого-то мотивацией работать и вообще что-нибудь делать.

**Comment by wldmr-key** [comment]
нормально. Только привести в соответствие нормам русского языка
