### ISSUE TITLE
Создать концептуальную схему данных предметной области (предварительную, конечно)

### ISSUE THREAD

**Issue by morozzov** [morozzov/StudentRating#6]

**Comment by morozzov** [comment]
# Концептуальная схема

![198976366-4ece79d7-e5bd-4ecb-953f-4727e7ae2518](https://user-images.githubusercontent.com/76492047/207236925-9705966f-5ba5-4f71-8292-58a176704d26.png)

**Comment by wldmr-key** [comment]
Правильно ли я понимаю, что создавать и закрывать поручения могут разные  преподаватели?
Поручение (работу на дне открытых дверей, например) может выполнять только один студент?
Кто изменяет учебные группы студентов?
Зачем хранится количество очков, если его можно посчитать?
Стоимость активности не имеет значения?
Активность не имеет автора?

подумай еще немного и обрати внимание, как твои функции отражаются в твоимх данных

**Comment by morozzov** [comment]
Внес изменения

**Comment by wldmr-key** [comment]
имеет смысл обсудить на консультации. Не уверен, что здесь все хорошо

**Comment by morozzov** [comment]
Поправил

**Comment by wldmr-key** [comment]
Возможно ты помнишь - мы обсуждали на консультациях необходимость сопровождать схемы пояснениями там, где это необходимо и нарисованные связи неочевидны из твоего описания предметной области.
вот связь между учебными группами и студентами очевидна - там слов не нужно
А, вот сущности "активности", "поручения", "отклики на поручения" явно не выделены в твоем описании. Поэтому, или там или здесь нужно разжевать читателю, почему получаются такие связи. Мне, например, до сих пор непонятно ))
И отклики/отказы действительно правильно подписаны?

**Comment by morozzov** [comment]
Внес правки

**Comment by wldmr-key** [comment]
неплохо, правда не в стандарте (глаголы на стрелках, множественные числа в сущностях)

**Comment by morozzov** [comment]
Привел к единственному числу

**Comment by wldmr-key** [comment]
Двоечник!!! ))
Сущности - существительные во множественном числе, связи - глаголы! Так должно быть!

**Comment by morozzov** [comment]
Теперь должно быть правильно..
