### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса (или API, если интерфейса нет)

### ISSUE THREAD

**Issue by morozzov** [morozzov/StudentRating#7]

**Comment by morozzov** [comment]
# Пользовательский интерфейс
## Авторизация
![image](https://user-images.githubusercontent.com/76492047/195975307-6133ad03-39a3-48fc-be05-a4d17c2141e1.png)
## Рейтинг
![image](https://user-images.githubusercontent.com/76492047/195974847-eca0c958-ba6d-44e2-b4cd-964f8a793969.png)
## Поручения
![image](https://user-images.githubusercontent.com/76492047/195974875-d262c346-c691-4b8a-8c83-2973f033bd86.png)
## Мои поручения
![image](https://user-images.githubusercontent.com/76492047/197837703-e0c28430-f056-45f3-b579-306adcbd69ec.png)
## Уведомления
![image](https://user-images.githubusercontent.com/76492047/195975050-2bd02ea1-d7d4-487c-9226-b587b0de95c2.png)
## Подменю
![image](https://user-images.githubusercontent.com/76492047/195974998-ae21f4cc-8cf8-4356-adb0-c3d887ceb185.png)
## Профиль
![image](https://user-images.githubusercontent.com/76492047/195975072-6dfdd007-24c7-49aa-a02b-d316fd1cc516.png)
## Настройки
![image](https://user-images.githubusercontent.com/76492047/195975323-109b2d43-c34a-4b82-8447-5e4c0f773607.png)

**Comment by wldmr-key** [comment]
Курсовая, конечно не посвящена пользовательскому интерфейсу, но хотелось бы более информативных экранов. И хинт: стоит даже скетчи заполнять более разнообразно

**Comment by morozzov** [comment]
Внес изменения

**Comment by wldmr-key** [comment]
прикольно ))
а отказы от поручений не штрафуются? ))

**Comment by morozzov** [comment]
Штрафуются) Будет добавлено в таблицу стоимости действий

**Comment by morozzov** [comment]
И в скобках в отказаться нужно написать, что это не бесплатно

**Comment by wldmr-key** [comment]
ок
